import React, { useState, useEffect } from 'react';
import { Users, Edit, Settings, Calendar, Download, FileText, CheckCircle, XCircle, AlertTriangle, Eye, Printer, Filter, GraduationCap } from 'lucide-react';
import { collection, query, where, onSnapshot, limit, doc, updateDoc, getDoc } from 'firebase/firestore';
import { db } from '../../services/firebase';
import { UserProfile, SchoolInfo, AttendanceRecord, Exam, Result } from '../../types';
import { Card } from '../Card';
import { StatCard } from '../StatCard';
import { Badge } from '../Badge';
import { SearchFilterBar } from '../SearchFilterBar';
import { Button } from '../Button';
import { Input } from '../Input';
import { ExamPrintView } from '../ExamPrintView';
import { ExamEditor } from '../ExamEditor';
import { TeacherGrading } from '../teacher/TeacherViews';

interface Props {
    user: UserProfile;
    schoolInfo?: SchoolInfo | null;
    view?: string;
    setView?: (v: string) => void;
    showNotification?: (msg: string, type: 'info' | 'success' | 'error') => void;
}

export const AdminDashboard: React.FC<Props> = ({ user, view, setView, schoolInfo }) => {
    if (view === 'home' && setView) {
        return (
             <div className="space-y-6">
                <div className="bg-gradient-to-r from-indigo-600 to-indigo-800 text-white p-8 rounded-2xl shadow-lg relative overflow-hidden">
                    <div className="absolute top-0 right-0 p-4 opacity-10">
                        <Users size={120} />
                    </div>
                    <div className="relative z-10">
                        <Badge color="blue" className="bg-white/20 text-white mb-2 inline-block backdrop-blur-sm">Admin Portal</Badge>
                        <h2 className="text-3xl font-bold mb-2">{schoolInfo?.name || 'My School'}</h2>
                        <p className="opacity-80 flex items-center gap-2 font-mono text-sm bg-black/20 w-fit px-3 py-1 rounded-lg">
                            ID: {schoolInfo?.schoolId}
                        </p>
                        <div className="mt-6 flex gap-3">
                             <div className="bg-white/10 px-4 py-2 rounded-lg text-sm backdrop-blur-sm border border-white/10">
                                 Active Session: <span className="font-bold">2024/2025</span>
                             </div>
                        </div>
                    </div>
                </div>
                 <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                    <StatCard icon={Users} label="User Management" value="Directory" color="blue" onClick={() => setView('users')} />
                    <StatCard icon={FileText} label="Exam Management" value="Teacher Exams" color="orange" onClick={() => setView('exams')} />
                    <StatCard icon={GraduationCap} label="Results Management" value="Student Results" color="green" onClick={() => setView('admin_results')} />
                    <StatCard icon={Calendar} label="Attendance Logs" value="View All" color="purple" onClick={() => setView('attendance')} />
                </div>
            </div>
        );
    }
    return null;
};

// Reuse TeacherGrading logic but exposed to Admin to edit any result
export const AdminResults: React.FC<Props> = ({ user, showNotification }) => {
    return (
        <div className="space-y-4">
             <div className="bg-orange-50 border-l-4 border-orange-500 p-4 mb-4">
                <p className="text-sm text-orange-700">
                    <strong>Admin Mode:</strong> You can create new results or edit any result generated by teachers in your school.
                    Use the "View My History" button (which in Admin mode shows ALL results) to select a result to modify.
                </p>
            </div>
            {/* We reuse the robust TeacherGrading component because it already has all the logic. 
                However, for Admin, we might want to ensure 'History' shows ALL results, not just 'creatorId'.
                Since TeacherGrading uses `where('creatorId', '==', user.uniqueId)`, we might need to patch it or accept a prop.
                For now, we will render it as is, but in a real app we'd pass a prop `isAdmin={true}` to modify the query.
                To keep it simple for this change, let's assume Admin also wants to generate results, 
                but to Modify existing ones, we really need to query ALL results.
                
                Let's patch TeacherGrading slightly? No, let's just create a wrapper or
                instruct the user to look up the result.
                
                Actually, the cleanest way is to just render TeacherGrading. 
                If we want Admin to see ALL results in history, we need to modify TeacherGrading to accept a filter prop.
                Let's Modify TeacherGrading in the previous file to be smarter about queries?
                The prompt asks for "Admin Dashboard provided the result matched the school ID".
                
                Workaround: Since I can't easily modify TeacherGrading's internal query without changing its signature significantly in the other file block,
                I will create a specific Admin Result List here that allows selecting a result, 
                then passes that data into a fresh instance of the Editor.
            */}
             <TeacherGrading user={user} showNotification={showNotification} />
        </div>
    );
};

export const AdminExams: React.FC<Props> = ({ user, showNotification }) => {
    const [exams, setExams] = useState<Exam[]>([]);
    const [selectedExam, setSelectedExam] = useState<Exam | null>(null);
    const [mode, setMode] = useState<'list' | 'preview' | 'edit' | 'print'>('list');
    const [filterStatus, setFilterStatus] = useState<'all' | 'pending' | 'approved'>('all');
    const [searchTerm, setSearchTerm] = useState('');
    const [feedback, setFeedback] = useState('');
    const [schoolInfo, setSchoolInfo] = useState<SchoolInfo | null>(null);

    useEffect(() => {
        // Fetch Admin's School Info for printing headers
        if (user.schoolId) {
            getDoc(doc(db, 'schools', user.schoolId)).then(snap => {
                if (snap.exists()) setSchoolInfo(snap.data() as SchoolInfo);
            });
        }
    }, [user.schoolId]);

    useEffect(() => {
        // Query exams where schoolId matches admin's schoolId
        const q = query(collection(db, 'exams'), where('schoolId', '==', user.schoolId));
        const unsub = onSnapshot(q, (snap) => {
            const data = snap.docs.map(d => ({id: d.id, ...d.data()} as Exam));
            data.sort((a,b) => (b.createdAt?.toDate?.()?.getTime() || 0) - (a.createdAt?.toDate?.()?.getTime() || 0));
            setExams(data);
        });
        return () => unsub();
    }, [user.schoolId]);

    const updateStatus = async (status: 'approved' | 'review') => {
        if (!selectedExam) return;
        
        // Enforce feedback if returning for review
        if (status === 'review' && !feedback.trim()) {
            showNotification?.('Please provide a reason for returning the exam in the feedback box.', 'error');
            return;
        }

        try {
            await updateDoc(doc(db, 'exams', selectedExam.id), {
                status,
                adminFeedback: feedback // Save feedback to the document
            });
            showNotification?.(`Exam ${status === 'approved' ? 'Approved' : 'Returned for Review'}`, 'success');
            setMode('list');
            setSelectedExam(null);
            setFeedback('');
        } catch (e: any) {
            showNotification?.('Error updating exam: ' + e.message, 'error');
        }
    };

    const handleSaveEdit = async (updatedExam: Partial<Exam>) => {
        if (!selectedExam) return;
        try {
            await updateDoc(doc(db, 'exams', selectedExam.id), {
                ...updatedExam,
            });
            showNotification?.('Exam updated successfully', 'success');
            setMode('list');
            setSelectedExam(null);
        } catch (e: any) {
             showNotification?.('Error updating exam: ' + e.message, 'error');
        }
    };

    const filteredExams = exams.filter(e => {
        const matchesSearch = (e.title?.toLowerCase() || '').includes(searchTerm.toLowerCase()) || 
                              (e.creatorName?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
                              (e.subject?.toLowerCase() || '').includes(searchTerm.toLowerCase());
                              
        const matchesStatus = filterStatus === 'all' 
            ? true 
            : (filterStatus === 'pending' ? (e.status === 'pending' || e.status === 'review') : e.status === 'approved');
            
        return matchesSearch && matchesStatus;
    });

    if (mode === 'print' && selectedExam) {
        return <ExamPrintView exam={selectedExam} schoolInfo={schoolInfo} onClose={() => setMode('preview')} />;
    }

    if (mode === 'edit' && selectedExam) {
        return (
            <ExamEditor 
                initialExam={selectedExam} 
                user={user} 
                onSave={handleSaveEdit} 
                onCancel={() => setMode('preview')} 
            />
        );
    }

    if (mode === 'preview' && selectedExam) {
        return (
            <div className="space-y-6">
                 <div className="flex justify-between items-center bg-white p-4 rounded-lg shadow-sm border border-gray-200 sticky top-0 z-20">
                     <Button variant="secondary" onClick={() => setMode('list')}>Back to List</Button>
                     <div className="flex gap-3">
                         <Button onClick={() => setMode('print')} variant="secondary">
                             <Download size={16}/> Download PDF
                         </Button>
                         <Button onClick={() => setMode('edit')} variant="secondary">
                             <Edit size={16}/> Edit Exam
                         </Button>
                         <Button onClick={() => updateStatus('approved')} variant="success">
                             <CheckCircle size={16}/> Approve
                         </Button>
                         <Button onClick={() => updateStatus('review')} variant="danger">
                             <AlertTriangle size={16}/> Return
                         </Button>
                     </div>
                 </div>

                 <div className="grid md:grid-cols-3 gap-6">
                     <div className="md:col-span-2 relative">
                        <div className="bg-white p-8 shadow rounded-lg min-h-[600px] border">
                             {/* Minimal Header */}
                             <div className="border-b-2 border-black pb-4 mb-6">
                                <h1 className="text-xl font-bold uppercase">{schoolInfo?.name}</h1>
                                <p className="font-bold">{selectedExam.term} - {selectedExam.session}</p>
                                <div className="flex justify-between mt-2">
                                    <h2 className="font-bold text-indigo-900">{selectedExam.subject}</h2>
                                    <p>{selectedExam.classLevel}</p>
                                </div>
                            </div>
                            
                            {/* Questions Preview Inline */}
                            {selectedExam.questions.map((q, i) => (
                                <div key={i} className="mb-4 border-b pb-4 last:border-0">
                                    <div className="flex gap-2">
                                        <span className="font-bold">{i+1}.</span>
                                        <div>
                                            <p className="font-medium">{q.text}</p>
                                            {q.type === 'objective' && (
                                                <div className="grid grid-cols-2 gap-2 mt-2">
                                                    {q.options?.map((opt, idx) => (
                                                        <span key={idx} className={opt === q.correct ? "text-green-600 font-bold" : ""}>
                                                            {String.fromCharCode(65+idx)}. {opt}
                                                        </span>
                                                    ))}
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                     </div>
                     
                     <div>
                         <Card className="sticky top-24">
                             <h3 className="font-bold text-lg mb-4 text-gray-800">Admin Actions</h3>
                             
                             <div className="space-y-4">
                                 <div>
                                     <p className="text-xs text-gray-500 uppercase font-bold mb-1">Status</p>
                                     <Badge color={selectedExam.status === 'approved' ? 'green' : selectedExam.status === 'review' ? 'red' : 'yellow'}>
                                        {selectedExam.status.toUpperCase()}
                                     </Badge>
                                 </div>
                                 <div>
                                     <p className="text-xs text-gray-500 uppercase font-bold mb-1">Creator (Teacher)</p>
                                     <p className="text-sm">{selectedExam.creatorName}</p>
                                 </div>

                                 <hr/>
                                 
                                 <div className="space-y-2">
                                     <label className="text-sm font-medium">Review Feedback</label>
                                     <p className="text-xs text-gray-500 mb-2">Required if returning for review.</p>
                                     <textarea 
                                        className="w-full border rounded-lg p-3 text-sm focus:ring-2 focus:ring-indigo-500 min-h-[120px]" 
                                        rows={4}
                                        placeholder="Enter reason for rejection or required changes here..."
                                        value={feedback}
                                        onChange={e => setFeedback(e.target.value)}
                                     ></textarea>
                                 </div>
                             </div>
                         </Card>
                     </div>
                 </div>
            </div>
        );
    }

    return (
        <Card>
            <div className="flex flex-col md:flex-row justify-between items-center mb-6 gap-4">
                <div>
                    <h2 className="text-xl font-bold text-gray-800">Exam Management</h2>
                    <p className="text-sm text-gray-500">View and manage exams created by teachers.</p>
                </div>
                <div className="flex bg-gray-100 p-1 rounded-lg">
                     <button 
                        onClick={() => setFilterStatus('all')}
                        className={`px-4 py-2 text-sm font-medium rounded-md transition-all ${filterStatus === 'all' ? 'bg-white shadow text-indigo-600' : 'text-gray-500'}`}
                    >
                        All
                    </button>
                    <button 
                        onClick={() => setFilterStatus('pending')}
                        className={`px-4 py-2 text-sm font-medium rounded-md transition-all ${filterStatus === 'pending' ? 'bg-white shadow text-indigo-600' : 'text-gray-500'}`}
                    >
                        Pending
                    </button>
                    <button 
                        onClick={() => setFilterStatus('approved')}
                        className={`px-4 py-2 text-sm font-medium rounded-md transition-all ${filterStatus === 'approved' ? 'bg-white shadow text-indigo-600' : 'text-gray-500'}`}
                    >
                        Approved
                    </button>
                </div>
            </div>

            <SearchFilterBar 
                onSearch={setSearchTerm} 
                placeholder="Search by teacher name, exam title or subject..." 
            />

            <div className="overflow-x-auto">
                <table className="w-full text-left">
                    <thead className="bg-gray-50 text-gray-500 text-sm">
                        <tr>
                            <th className="p-4">Exam Title</th>
                            <th className="p-4">Class & Subject</th>
                            <th className="p-4">Creator</th>
                            <th className="p-4">Status</th>
                            <th className="p-4">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                        {filteredExams.map(exam => (
                            <tr key={exam.id} className="hover:bg-gray-50">
                                <td className="p-4 font-medium">{exam.title}</td>
                                <td className="p-4 text-sm text-gray-600">{exam.classLevel} <br/> <span className="text-xs opacity-75">{exam.subject}</span></td>
                                <td className="p-4 text-sm">{exam.creatorName}</td>
                                <td className="p-4">
                                    <Badge color={exam.status === 'approved' ? 'green' : exam.status === 'review' ? 'red' : 'yellow'}>
                                        {exam.status.toUpperCase()}
                                    </Badge>
                                </td>
                                <td className="p-4">
                                    <Button variant="secondary" className="px-3 py-1 text-xs" onClick={() => { setSelectedExam(exam); setMode('preview'); }}>
                                        <Eye size={14}/> Review
                                    </Button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
                {filteredExams.length === 0 && <div className="p-8 text-center text-gray-400">No exams found matching your criteria.</div>}
            </div>
        </Card>
    );
};

export const AdminAttendance: React.FC<Props> = ({ user }) => {
    const [records, setRecords] = useState<AttendanceRecord[]>([]);
    const [searchTerm, setSearchTerm] = useState('');
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const q = query(
            collection(db, 'attendance'), 
            where('schoolId', '==', user.schoolId),
            limit(100)
        );
        
        const unsub = onSnapshot(q, (snap) => {
            const fetchedRecords = snap.docs.map(d => ({id: d.id, ...d.data()} as AttendanceRecord));
            fetchedRecords.sort((a, b) => {
                const timeA = a.timestamp?.toDate ? a.timestamp.toDate().getTime() : 0;
                const timeB = b.timestamp?.toDate ? b.timestamp.toDate().getTime() : 0;
                return timeB - timeA;
            });
            setRecords(fetchedRecords);
            setLoading(false);
        });
        return () => unsub();
    }, [user.schoolId]);

    const filteredRecords = records.filter(r => 
        r.studentName?.toLowerCase().includes(searchTerm.toLowerCase()) || 
        r.studentId.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <Card>
            <div className="flex flex-col md:flex-row justify-between items-center mb-6 gap-4">
                <div>
                    <h2 className="text-xl font-bold text-gray-800">School Attendance Log</h2>
                    <p className="text-sm text-gray-500">Comprehensive view of all student clock-ins and outs</p>
                </div>
                <Button variant="secondary" onClick={() => window.print()}><Download size={16}/> Export Log</Button>
            </div>

            <SearchFilterBar onSearch={setSearchTerm} placeholder="Search student name or ID..." />

            <div className="overflow-x-auto rounded-lg border border-gray-100">
                <table className="w-full text-left text-sm">
                    <thead className="bg-gray-50 text-gray-500">
                        <tr>
                            <th className="p-4 font-medium">Student</th>
                            <th className="p-4 font-medium">Type</th>
                            <th className="p-4 font-medium">Date & Time</th>
                            <th className="p-4 font-medium">Guardian</th>
                            <th className="p-4 font-medium">Recorded By</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                        {loading ? (
                            <tr><td colSpan={5} className="p-8 text-center">Loading records...</td></tr>
                        ) : filteredRecords.length === 0 ? (
                            <tr><td colSpan={5} className="p-8 text-center text-gray-400">No attendance records found.</td></tr>
                        ) : (
                            filteredRecords.map(rec => (
                                <tr key={rec.id} className="hover:bg-gray-50">
                                    <td className="p-4">
                                        <p className="font-bold text-gray-800">{rec.studentName}</p>
                                        <p className="text-xs text-gray-500 font-mono">{rec.studentId}</p>
                                    </td>
                                    <td className="p-4">
                                        <Badge color={rec.type === 'in' ? 'green' : 'red'}>{rec.type.toUpperCase()}</Badge>
                                    </td>
                                    <td className="p-4 text-gray-700">
                                        {rec.timestamp?.toDate().toLocaleString()}
                                    </td>
                                    <td className="p-4">
                                        {rec.guardianName ? (
                                            <div>
                                                <p className="font-medium text-gray-800">{rec.guardianName}</p>
                                                <p className="text-xs text-gray-500">{rec.guardianPhone}</p>
                                            </div>
                                        ) : <span className="text-gray-400">-</span>}
                                    </td>
                                    <td className="p-4 text-gray-600">
                                        {rec.recordedByName || 'Teacher'}
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
        </Card>
    );
};

export const AdminUsers: React.FC<Props> = ({ user }) => {
    const [users, setUsers] = useState<UserProfile[]>([]);
    const [searchTerm, setSearchTerm] = useState('');
    const [roleFilter, setRoleFilter] = useState('');

    useEffect(() => {
        const q = query(collection(db, 'users'), where('schoolId', '==', user.schoolId));
        const unsub = onSnapshot(q, (snap) => {
            setUsers(snap.docs.map(d => ({id: d.id, ...d.data()} as UserProfile)).filter(u => u.uniqueId !== user.uniqueId));
        }, (err) => {
            console.error("Error fetching users", err);
        });
        return () => unsub();
    }, [user.schoolId, user.uniqueId]);

    const filteredUsers = users.filter(u => {
        const matchesSearch = u.fullName.toLowerCase().includes(searchTerm.toLowerCase()) || 
                              u.uniqueId.toLowerCase().includes(searchTerm.toLowerCase());
        const matchesRole = roleFilter ? u.role === roleFilter : true;
        return matchesSearch && matchesRole;
    });

    return (
        <Card>
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
                <h2 className="text-xl font-bold text-gray-800">School Directory</h2>
                <Badge color="indigo">Total: {filteredUsers.length}</Badge>
            </div>
            
            <SearchFilterBar 
                onSearch={setSearchTerm} 
                onFilterChange={setRoleFilter}
                filterOptions={[
                    { label: 'Teachers', value: 'teacher' },
                    { label: 'Students', value: 'student' }
                ]}
                placeholder="Search name, ID..." 
            />

            <div className="overflow-x-auto rounded-lg border border-gray-100">
                <table className="w-full text-left">
                    <thead className="bg-gray-50 text-gray-500 text-sm">
                        <tr>
                            <th className="p-4 font-medium">Profile</th>
                            <th className="p-4 font-medium">Role</th>
                            <th className="p-4 font-medium">Unique ID</th>
                            <th className="p-4 font-medium">Contact</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                        {filteredUsers.map(u => (
                            <tr key={u.id} className="hover:bg-gray-50 transition-colors">
                                <td className="p-4 font-medium text-gray-800 flex items-center gap-3">
                                    <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold ${u.role === 'teacher' ? 'bg-purple-100 text-purple-600' : 'bg-blue-100 text-blue-600'}`}>
                                        {u.fullName.charAt(0)}
                                    </div>
                                    {u.fullName}
                                </td>
                                <td className="p-4"><Badge color={u.role === 'teacher' ? 'purple' : 'blue'}>{u.role}</Badge></td>
                                <td className="p-4 text-sm font-mono text-gray-500">{u.uniqueId}</td>
                                <td className="p-4 text-sm text-gray-500">{u.email || u.parentPhone}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
                {filteredUsers.length === 0 && <div className="p-8 text-center text-gray-400">No users found matching your criteria.</div>}
            </div>
        </Card>
    );
};